services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=energy_dashboard
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=energy_dashboard
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - TIMESCALE_ENABLED=True
      - CHUNK_TIME_INTERVAL=1 day
      - EIA_API_KEY=${EIA_API_KEY}
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

volumes:
  timescaledb_data: 